# Use this docker-compose file as:
#
#  docker-compose -f docker-compose.yml -f docker-compose-reverseproxy.yml up -d
#
#
# This command creates one
# compose 'project' consisting of three containers
#
#  1. The PostgreSQL data  container
#  2. The LedgerSMB application container
#  3. The Nginx reverse proxy container
#
# In addition to publishing LedgerSMB on port 5762 on localhost,
# this project also publishes Nginx's reverse proxied content on
# port 8080 on localhost

version: "3.2"
services:
  proxy:
    depends_on:
      - lsmb
    image: nginx:1-alpine
    volumes:
      - "lsmbdata:/srv/ledgersmb"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    # Comment the line below to stop the container from restarting on boot
    # unless it was manually stopped
    restart: unless-stopped
  lsmb:
    volumes:
      - "lsmbdata:/srv/ledgersmb"

volumes:
  lsmbdata:
