name: Docker Image cleanup

on:
  push:
  workflow_dispatch:
  schedule:
    # Schedule for five minutes after the hour, every Friday
    - cron: '10 3 * * 5'

jobs:
  cleanup:
    if: github.repository_owner == 'ledgersmb'
    runs-on: ubuntu-latest
    steps:
    - name: ghcr.io cleanup action
      uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        packages: ledgersmb
